name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:  # Add this to allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # Add this block to grant write permissions
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py

      - name: Commit and push changes
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@aym-n.github.io"
          git config --global user.name "GitHub Actions Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
